
= Capítulo 13. Ser el peor

[quote, Pablo Picasso.]
Siempre estoy haciendo lo que no puedo hacer para poder aprender cómo hacerlo.

Cuando comienzas por primera vez a trabajar, existe esa emoción de empezar a saber de forma asertiva todo aquello que te va a ser útil para tu vida laboral, sabes que de alguna forma u otra aprenderás de los miembros de tu equipo que ya cuentan con algo de experiencia y que en algunos casos tú también podrás obtener el mismo conocimiento para poder aportar al proyecto.

También, sabes que deberás de poner un esfuerzo superior al de tus demás compañeros pues tienes que alcanzar los a un punto en donde te permita ser productivo y poder aportar algo, ese esfuerzo lo haces o lo harás sin pensarlo, sabes que tienes que hacerlo porque sino simple sencillamente te estancarás.

Pues bien, esta misma sensación se repetirá a cada nuevo lugar que entres en donde el equipo de trabajo con el que estés participando sea intelectualmente superior o estén afrontando retos que hasta el momento tú no has enfrentado. Siempre tendrás algo que aprender de tu equipo o del problema que estás resolviendo, y tendrás que poner un empeño mayor que los demás, para poder dar una solución, o simple y sencillamente aportar algo a la inmensidad de un proyecto.

Tal vez, en algún momento cuando ya conozcas un grupo de herramientas y tengas la experiencia para afrontar ciertos problemas, estarás buscando oportunidades que posiblemente alimenten tu economía, lo cual no está mal, pues ya cuentas con los elementos para hacerlo. Si bien, lo que te quiero comentar en esta ocasión es el hecho de que cuando eso ocurre podrías entrar peligrosamente a una zona de comfort, que te permita desempeñarte en elementos que tú ya conoces, y no te permitas a ti mismo aprender más o sentirte de nuevo como aquel novato con la emoción de aprender algo nuevo.

Mi intención en esta ocasión es resaltar la importancia de volver empezar en equipos en donde somos los que más camino tenemos que recorrer, eso genera una experiencia y nos permite encontrar formas alternativas de ponernos al corriente con las habilidades de un equipo de trabajo. Y es que hay que pensarlo bien, de qué sirve ser el mejor integrantes de un equipo si ya todo lo sabes y no tienes nada que aportar a los demás, o bien no estás aprendiendo de alguien más, es muy difícil que siendo el mejor elemento de tu equipo veas fácilmente como superarte pues no tienes a nadie con quien comparar o quien seguir, esto último es lo que genera la comodidad, pues tampoco vas a tener una competencia aparente.

Siempre será mejor ser el peor miembro de un equipo, pues te ayudará a reactivar todos esos mecanismos de estudio y te motivará a estar en aprendizaje continuo.

Cada vez que entras a una organización seguramente podrás verte a ti mismo con un perfil de conocimiento en comparación con los que ya están ahí, y conforme pase el tiempo podrás aprender lo mismo que los demás, y posiblemente migres a otra organización en donde comienzas de nuevo, siendo así la sugerencia es que busques esas organizaciones a las cuales sea muy difícil entrar, pues siempre serás el novato con ganas de aprender y llegar a ser como los demás.

La forma correcta de avanzar es usando esas fortalezas individuales que ya adquiriste con el entusiasmo con el que entraste, y cooperar con los elementos que te son asignados por los miembros de tu equipo.

Ser el peor no se trata de superioridad o fuerza, se trata de ritmo sostenido para poder ayudar a tus colegas, pues ellos te habrán ayudado a corregir tus errores, a cometer errores de forma segura y recuperarte lo antes posible, y lo que tu tienes que ofrecer es tu mejor esfuerzo para estar a la altura de las situaciones difíciles, no se trata tampoco de jerarquías si no de la suma de las colaboraciones de varios profesionales.
