
=== Capítulo 2. Invierte en ti

[quote, El autor]
...Considero que la buena educación(incluso la autodidacta) cuesta tiempo, dinero y/o esfuerzo...

Uno de los aspectos más importantes en la carrera de cualquier profesional, indistintamente del giro que ejerza, es y será mejorarse a si mismo. Existen muchas maneras de hacerlo, específicamente en el área de tecnología existen muchos recursos con los cuales uno puede lograrlo, hoy en día contamos con artículos, tutoriales, cursos en línea, diplomados, escuelas, etcétera.

Sin embargo, recuerdo muy bien cuando estaba en una etapa de aprendiz y estudiante, y muchos de los recursos disponibles estaban a un precio que yo no podía pagar en ese momento. Y seguramente puede ser la situación de cualquier persona que decida emprender una carrera como profesional de software, o bien, decida cambiarse de plataforma tecnológica.

Una de las cosas que pude notar durante el aprendizaje de varias de estas plataformas tecnológicas fue el hecho de que tenía que invertir algo en ellas, y definitivamente la inversión tenía que ser proporcional al beneficio que quería obtener. Me refiero a que una inversión pobre me estaría remunerando pobremente también, no quiero que me mal entiendan, a lo que me refiero esa la situación o el contexto que se presentan mientras eres un aprendiz y estás comenzando con pocos recursos.

Me quiero enfocar específicamente a lo que mencioné al principio, tres elementos que podrías bien balancear para obtener un gran beneficio, entiendo que durante la etapa de principiante los recursos económicos son escasos y en algunos casos nulos, por eso me quiero centrar en los otros dos, y a modo de resumen tocaré el aspecto monetario.

==== Esfuerzo

Definitivamente tienes que comprometerte con lo que estás haciendo y considerar que los elementos fáciles de obtener no te entregarán un gran valor; me refiero a el hecho de que muchos de los recursos, específicamente aquellos que muestran tecnología, los que verdaderamente valen la pena están en otro idioma y tendrás que considerar el hecho de aprenderlo de alguna u otra manera, para lo cual existen recursos escolares o gratuitos que te ayudan a sobreentender lo más esencial, con lo que podrías avanzar.

Me refiero también, a la situación en donde vas a tener que leer una y otra vez, buscar conceptos muy básicos, buscar a las personas adecuadas que te puedan resolver alguna duda, los libros de texto que tengas disponible en alguna biblioteca a la cual puedas tener acceso, inclusive crear grupos de trabajo que te ayuden a exponer y compartir lo que sabes para reafirmarlo y comprobar realmente que dominas el tema.

Actualmente, existe una brecha de comunicaciones acortada que nos ayuda a conectar con personas que están desarrollando tecnología, y no he visto a nadie que se niegue a resolver alguna duda de lo que están haciendo; lo que quiero decir es que puedes acercarte a comunidades de software que te permitan aprender al respecto de alguna plataforma que te interese.

Tendrás que experimentar con aquellos conceptos, recursos y elementos que vayas encontrando a tu paso para cerciorarte es que en verdad funciona aquello que estás tratando de aprender, sin embargo, mi sugerencia siempre será referirte a la documentación original de cada uno de los proyectos de software que estés probando, pues en cada uno de ellos se considera el aspecto del uso básico de la herramienta un lenguaje que estés experimentando.

Si ya leíste o revisaste algún video al respecto del tema, definitivamente tendrás que buscar alguna otra lectura oh recurso que te permita comparar o reafirmar lo que has aprendido, lo que me refiero aquí es que no será suficiente ver o conocer algún concepto de una sola y única vez, sino que será necesario que loco dejes con algunas otras fuentes y que a su vez también vayas explorando los elementos teóricos que lo sostienen, pues es aquí en donde creo que está el verdadero conocimiento, debes de cerciorarte qué comprendes muy bien aquello que estás tratando de aprender, y si por alguna razón no lo estás logrando entonces deberás cuestionarte los conceptos en los cuales se está sustentando esa herramienta, plataforma o tecnología que estás aprendiendo. Con lo cual, poco a poco te irás dando cuenta que existen ciertos elementos teóricos que debiste aprender en algún momento, y que ahora es tiempo de reforzar.

Entre mayor sea el esfuerzo que inviertas al aprender algún elemento, mayor será el beneficio que pudieras obtener de este.

==== Tiempo

Uno de los elementos que más tienes cuando estás iniciando es el tiempo, Y deberás aprovecharlo de la mejor manera, investigando, leyendo O bien practicando.

Creo que uno de los hechos que marca la diferencia en algunas carreras conocidas de los profesionales de software es la forma en la que invierten su tiempo para avanzar de alguna manera, me refiero a que deberás de usarlo para conocer no solamente de tecnología, sino también de elementos que conciernen a las humanidades, la literatura, tal vez la biología, la sociedad, incluso podría decirte algunos elementos relacionados con el ocio y la cultura, pues es bien conocido que entre los desarrolladores se acostumbra una buena taza de café O un buen tarro de cerveza, de un videojuego inclusive, Y deberás de conocer al respecto de esto o algunas otras actividades que te permitan relacionarte con muchas más personas que incluso no compartan tus mismos gustos.

Deberás de darte la oportunidad de conocer más al respecto de la cultura digital y todo lo que lo rodea, de los elementos E ideas que puedes adoptar Y probar para usar en tu vida diaria, Aplicaciones que existen hoy en día y programas que harán las cosas por ti.

En definitiva, lo que creo es que deberás ser muy cuidadoso al explorar ciertas herramientas en las cuales tendrás que invertir un espacio en tu día Y que seguramente te beneficiarán una vez que las hayas dominado o aprendido, bien se dice que una herramienta puede ahorrarte mucho tiempo y esfuerzo cuando verdaderamente cumple su función.

Te encontrarás en algún momento con el problema en donde pareciera ser que el tiempo que tienes disponible es muy poco O casi nulo, piénsalo bien pues tal vez tienes espacios o huecos de tiempo que puedes aprovechar para avanzar en algo que estés haciendo, Y no me refiero a llevarte una computadora a todas partes para que estés programando, me refiero más al hecho de que lleves contigo un libro O un medio de reproducción de audio que te permita leer al respecto de un tema mientras estás viajando en el transporte público, O bien escuchar algún podcast de tecnología O programación que te dé de alguna idea de cómo se expresan otras personas al respecto, incluso en el mejor de los casos podrás descargar videos que podrás reproducir en algún dispositivo con los que se encuentran actualmente Y verlos durante el camino al trabajo, a la escuela, O a tu casa.

Considera una cuenta muy simple en donde un día tiene 24 horas, si tú durmieras ocho horas Y estuvieras en tu escuela O en tu trabajo Durante otras ocho horas Y el tiempo de transporte te tomará alrededor de tres horas, aún te quedan cinco de las cuales podrías tomar tres para tus alimentos Y actividades cotidianas, te quedan aún 2 horas al día que puedes usar en ti, en tu carrera como profesional, ya sea con algún libro o curso, con un video o simplemente aprendiendo un lenguaje nuevo, y si sólo lo sumas entonces tendrás 14 horas a la semana. Pero reflexiona, siendo honestos no dormimos 8 horas, yo diría que a veces es menos, y no trabajamos 8 horas, incluso también podría decir que es menos, entonces piénsalo de nuevo por un momento por que tal vez tengas más tiempo del que planteo aquí.

Lo que digo es que como lo sugirió robert c. Martin en el libro _”the clean coder”_, tienes que dedicarle un tiempo sustancioso a ti como profesional, y a tu carrera como lo que eres y representas, deberás dedicarle también un tiempo a descansar y dormir, inspirarte y retomar energía para el aspecto creativo, a planear lo que tienes que hacer entre trabajo y en tu persona, revisando los objetivos que has logrado de forma periódica.

Todo esto te servirá para que administres correctamente uno de los recursos que jamás se recupera, el que no puedes comprar y que te gustaría aprovechar con las personas buenas actividades que más te gustan.

==== Dinero

Definitivamente, si tienes la posibilidad de acortar un camino literal en tu carrera, deberías hacerlo y enfocarlo en aquello que deseas lograr.

No todos tenemos esta oportunidad, sin embargo, siempre será bueno ahorrar para invertir en uno mismo a través de algún curso o una conferencia, que tal vez sea gratuita pero que no se encuentra en tu localidad, si no en alguna parte muy lejana en la cual tendrás que comprar algún boleto de autobús o de avión para poder asistir.

A lo que me refiero es que definitivamente tendrás que invertir recursos económicos en tu carrera, pero tendrás que ser diligente con lo que gastas y observar detenidamente que quieres lograr con lo que estás gastando.

Actualmente, la cantidad de recursos que puedes acceder y que tienen un precio modesto son muchos, desde videos con un gran contenido y edición que te permiten digerir mucho conocimiento, libros que puedes encontrar en descuentos en algunos días, o talleres cortos que ofrecen un conocimiento muy particular aunque no sea referente a tecnología.

Considera lo siguiente por un momento, seguramente has usado algún software entre equipo de cómputo o en algún dispositivo móvil, el cual has disfrutado y usado, o inclusive te ha sacado de algún apuro, este software es gratuito; ahora bien, considera el software que tú estás haciendo y que otras personas podrían ocupar para beneficiarse por resolver un problema justo como tú lo hiciste, si tú no estás pagando por un software que estás usando y que te es muy útil,¿porque alguien más tendría que pagar el software que tu haces, con la calidad cualquiera que sea, que puedes ofrecer? No quiero que me mal entiendan, a lo que me refiero es que aveces hay software que podríamos comprar y esta en nuestras manos, los precios de algunas aplicaciones son muy pequeñas y alcanzables por muchas personas, tu como desarrollador de software deberías de invertir también en software, deberías de comprar el software que otras personas hacen o bien contribuir de forma económica a las aportaciones que solicitan.

Todo esto podrá crear una cultura que le permita a cualquier individuo comprar software de forma muy común, justo como hoy compramos cualquier artículo, la gente también podrá comprar o colaborar con el software que tú estás haciendo. Al final del día, este es el tema al que quiero llegar, el poder transmitir la cultura de adquirir software o servicios basados en software que verdaderamente aportan un valor, resuelvan un problema o una necesidad, o generen alguna ganancia o retribución aún a comunidad de personas, que no necesariamente tendría que ser económica.
