
=== Capítulo 6. Tu lugar en un equipo.En algún momento del tiempo alguien dijo:
[quote, nelson mandela]
El hombre valiente no es el que no siente miedo, sino aquel que conquista ese miedo.

Creo que saber nada es un buen comienzo, realmente saber nada o poco puede ser manejable y a lo mejor con esfuerzo y dedicación se resuelve, pero creer que sabes mucho y verdaderamente no es así entonces creo que puede ser un mal comienzo.

Aquí quiero dedicar un espacio a la comprensión de todas las personas que se unen a algún equipo de trabajo, podría decirse que en especial a los novatos, pero creo que cabe en muchos inclusive siendo experimentados. A lo que me refiero es que verdaderamente tienes ciertas habilidades que otras personas dentro de un equipo de trabajo no tienen y que podría usar para tener un lugar que le permita a un equipo confiar en ti, sin embargo, debes de saber que estas habilidades o conocimientos deben ser previos al ingreso y que es tu responsabilidad adquirirlos, ya que si nadie más sabe hacer lo que tú haces no importa lo pequeño que sea entonces podrás ayudar.

También tienes que saber que la frescura de las ideas en cualquier equipo de trabajo puede ser motivante, e incluso sorprendente, cuando alguien que apenas entra a un equipo puede exponer la forma en como lo resolvería, dando un punto de vista demasiado objetivo de las cosas.

Además, en todos los equipos de trabajo sin importar la experiencia que tengas los demás, siempre habrá tareas muy pequeñas que se estén realizando, y es aquí en donde puedes intervenir y seguramente aprenderás mucho de todas esas cosas que para los demás parecerían insignificantes, pero que para ti serán importantes pues tendrás que aprender a dominarlas y conocer profundamente cómo es que operan y la razón por la cual están ahí.

Es por esto que todos las herramientas nuevas que tu conozcas siempre serán bienvenidas en un equipo de trabajo en donde seguramente el pasar del tiempo no les ha permitido explorar esas oportunidades. Ten la confianza de que muchas de las cosas que tú has hecho o usado también pueden servir como herramientas de trabajo para ti y tus nuevos compañeros.

¿Que vas a tener que hacer? Pues bien, ser extremadamente observador en los detalles que te permitan una oportunidad para preguntar al respecto de tecnología o para aprender alguna que ya se esté usando en algún equipo, y profundizar en ella. Seguramente, en el momento en el que tú entres o estés comenzando a trabajar con algún equipo verás que se usan ciertos elementos comunes, es ahí en donde tienes que ir creando tus oportunidades y tienes que ver que están usando y buscar al respecto de lo que se está usando, hoy en día eso es demasiado sencillo, pues sólo basta el nombre de algunas aplicaciones, lenguajes o herramientas para poder saber qué hacen, pero habrá ocasiones en las que seguramente no encontrarás mucha información o algo o que te diga exactamente qué es y es entonces donde tendrás que preguntar.

Con todo esto, quiero que sepas que la única forma de poder lograr algo que verdaderamente te ayude a ser parte de un equipo será la pro-actividad que le dediques, pero nuevamente, se observador y siempre indaga, válida con tu base de conocimiento y conceptos teóricos, y sacar algunas conclusiones que podrías bien cuestionar con alguno de tus compañeros que tienen más experiencia que tú. Debes tener la iniciativa de ir absorbiendo cada vez más conocimiento, técnicas y métodos que seguramente te ayudarán a ti, pero mejor aún podrán hacer que colabores con un equipo de trabajo muy rápidamente.

También, habrá ocasiones en las que seguramente estés platicando al respecto de algún tema en particular que sea de tu interés y muy fácilmente podrás preguntar al respecto, y si entre el grupo de personas se encuentra alguien que le apasiona este tema seguramente te dará algunas respuestas inmediatas, y podrá compartirte algo de lo que ha experimentado. Aún así, no te quedes sólo con lo que te dicen siempre un paso más adelante y profundiza en el tema, aterrizando a los conceptos esenciales y busca si hay algo parecido a lo que has conocido.

Aunque no lo creas, tu opinión siempre es muy importante pues nos hace recordar los momentos en los que nosotros estuvimos en el mismo lugar, en donde estábamos comenzando, y seguramente eso podrá inspirar a ciertas personas a darte alguna sugerencia que les hubiera gustado escuchar cuando estaban en tu posición, es por esto que siempre recomendaré qué cualquier opinión, experiencia, sensación u observación que tengas, la expreses de forma abierta y honesta, literal por sorpresa a las personas o bien darles una satisfacción en la cual puedes notarse que están haciendo bien su trabajo con lo que te están enseñando.

Por último, aunque no menos importante necesito saber que en todos los equipos de trabajo siempre se necesita gente que aprenda o que tenga poco experiencia ya sea como profesional o en el área en el que se está desempeñando, pues algunos elementos de curiosidad pueden ayudar a implementar soluciones en las cuales un equipo no ha visto por la inercia del trabajo o bien porque simplemente no veían dichos oportunidades.

Hay que saber una cosa más, la emoción y pasión de todos los aprendices siempre se transmite hacia el equipo, es renovaste y refrescante ver como esa sensación de aprender cosas nuevas se contagia hacia aquello que ya hemos pasado por esto, y mejor aún, ver que lo que hemos enseñado ha sido bien aprendido, así que esmérate en hacer sentir orgullosos a tus mentores y a darles el mérito que merecen.
