
=== Capítulo 2. Invierte en ti

> ...Considero que la buena educación(incluso la autodidacta) cuesta tiempo, dinero y/o esfuerzo...
> - El autor

Uno de los aspectos más importantes en la carrera de cualquier profesional, indistintamente del giro que ejerza, es y será mejorarse a si mismo. Existen muchas maneras de hacerlo, específicamente en el área de tecnología existen muchos recursos con los cuales uno puede lograrlo, hoy en día contamos con artículos, tutoriales, cursos en línea, diplomados, escuelas, etcétera.

Sin embargo, recuerdo muy bien cuando estaba en una etapa de aprendiz y estudiante, y muchos de los recursos disponibles estaban a un precio que yo no podía pagar en ese momento. Y seguramente puede ser la situación de cualquier persona que decida emprender una carrera como profesional de software, o bien, decida cambiarse de plataforma tecnológica.

Una de las cosas que pude notar durante el aprendizaje de varias de estas plataformas tecnológicas fue el hecho de que tenía que invertir algo en ellas, y definitivamente la inversión tenía que ser proporcional al beneficio que quería obtener. Me refiero a que una inversión pobre me estaría remunerando pobremente también, no quiero que me mal entiendan, a lo que me refiero esa la situación o el contexto que se presentan mientras eres un aprendiz y estás comenzando con pocos recursos.

Me quiero enfocar específicamente a lo que mencioné al principio, tres elementos que podrías bien balancear para obtener un gran beneficio, entiendo que durante la etapa de principiante los recursos económicos son escasos y en algunos casos nulos, por eso me quiero centrar en los otros dos, y a modo de resumen tocaré el aspecto monetario.

==== Esfuerzo

Definitivamente tienes que comprometerte con lo que estás haciendo y considerar que los elementos fáciles de obtener no te entregarán un gran valor; me refiero a el hecho de que muchos de los recursos, específicamente aquellos que muestran tecnología, los que verdaderamente valen la pena están en otro idioma y tendrás que considerar el hecho de aprenderlo de alguna u otra manera, para lo cual existen recursos escolares o gratuitos que te ayudan a sobreentender lo más esencial, con lo que podrías avanzar.

Me refiero también, a la situación en donde vas a tener que leer una y otra vez, buscar conceptos muy básicos, buscar a las personas adecuadas que te puedan resolver alguna duda, los libros de texto que tengas disponible en alguna biblioteca a la cual puedas tener acceso, inclusive crear grupos de trabajo que te ayuden a exponer y compartir lo que sabes para reafirmarlo y comprobar realmente que dominas el tema.

Actualmente, existe una brecha de comunicaciones acortada que nos ayuda a conectar con personas que están desarrollando tecnología, y no he visto a nadie que se niegue a resolver alguna duda de lo que están haciendo; lo que quiero decir es que puedes acercarte a comunidades de software que te permitan aprender al respecto de alguna plataforma que te interese.

Tendrás que experimentar con aquellos conceptos, recursos y elementos que vayas encontrando a tu paso para cerciorarte es que en verdad funciona aquello que estás tratando de aprender, sin embargo, mi sugerencia siempre será referirte a la documentación original de cada uno de los proyectos de software que estés probando, pues en cada uno de ellos se considera el aspecto del uso básico de la herramienta un lenguaje que estés experimentando.

Si ya leíste o revisaste algún video al respecto del tema, definitivamente tendrás que buscar alguna otra lectura oh recurso que te permita comparar o reafirmar lo que has aprendido, lo que me refiero aquí es que no será suficiente ver o conocer algún concepto de una sola y única vez, sino que será necesario que loco dejes con algunas otras fuentes y que a su vez también vayas explorando los elementos teóricos que lo sostienen, pues es aquí en donde creo que está el verdadero conocimiento, debes de cerciorarte qué comprendes muy bien aquello que estás tratando de aprender, y si por alguna razón no lo estás logrando entonces deberás cuestionarte los conceptos en los cuales se está sustentando esa herramienta, plataforma o tecnología que estás aprendiendo. Con lo cual, poco a poco te irás dando cuenta que existen ciertos elementos teóricos que debiste aprender en algún momento, y que ahora es tiempo de reforzar.

Entre mayor sea el esfuerzo que inviertas al aprender algún elemento, mayor será el beneficio que pudieras obtener de este.

==== Tiempo

Uno de los elementos que más tienes cuando estás estudiando es el tiempo,

==== dinero

Definitivamente, si tienes la posibilidad de acortar un camino literal en tu carrera, deberías hacerlo y enfocarlo en aquello que deseas lograr.
