
= Capítulo 3. No escuches a nadie

[quote, Theodore Roosevelt]
En cualquier momento de decisión, lo mejor que puedes hacer es lo correcto, la mejor cosa siguiente es lo incorrecto y lo peor que puedes hacer es nada.

== No escuches a tus compañeros/amigos

Hace mucho tiempo después de que salí de la universidad, platiqué con algunos de mis compañeros con los que había estudiado y dado que ya habían pasado algunos años desde que regresamos, vino a la mesa la inevitable platicar al respecto de qué estás haciendo o en qué estás trabajando ahorita, esta plática puede resultar un poco incómoda dependiendo de donde la tomes, quiero explicar porqué, parafraseando un poco la charla iba algo así:

[horizontal]
Omar:: oigan, y que están haciendo ahorita? Ya tiene algunos años que salimos de la universidad...
Víctor:: yo ahorita estoy de gerente de administración tecnológica...
Nadia:: yo soy líder de proyecto en la empresa donde trabajo...
Roberto:: yo estoy de project manager en la implementación de un erp...
Omar:: yo soy encargado de la administración de ser servidores e infraestructura para varias empresas...
Yo:: yo estoy programando!!!
Todos:: queeeeeé?
Nadia:: acaso no has pedido un ascenso?
Víctor:: aún sigues programando?
Omar:: por qué no has avanzado?

La reacción de mis compañeros podría parecer muy obvia, bajo el contexto en el cual posiblemente ellos están formando una carrera, sin embargo, hay algo que ellos no saben porque posiblemente no han visto, y he aquí varias preguntas que deberías de hacer:

¿Qué significa ascender?, ¿Qué significa seguir programando?, ¿Qué es realmente avanzar como profesional?, ¿Qué es crecer?, ¿Qué es el éxito?, ¿Qué es lo que realmente quieres hacer o conseguir?

Lo que ellos no sabían es que había crecido, había avanzado, inclusive podría apostar que en ese momento mi ingreso económico por mi trabajo era similar o inclusive un poco superior al de alguno de ellos, porque realmente lo que ellos estaban buscando era un reconocimiento, una posición o un título elegante que les permitiera describir su trabajo, y yo solamente estuve buscando nuevas formas de resolver problemas, que me permitieran enfrentar retos verdaderamente interesantes y obtener soluciones con todo lo que iba aprendiendo a mi paso.

Un título nobiliario no te hace mejor o peor en el contexto del desarrollo de software; por lo menos, yo realmente había conseguido avanzar pues ya conocía más de un lenguaje de programación con el que podía resolver algún problema, ya dominaba un par de frameworks que me permitían ser productivo al desarrollar alguna aplicación, conocía de algunas técnicas y métodos que me permitían garantizar la calidad del software que estaba desarrollando, conocía algunas metodologías de trabajo, enseñaba a mis compañeros, conocía cada vez a más gente interesante que resolvía problemas verdaderamente difíciles, yo enfrentaba restos que antes ni siquiera podía imaginar, ¿y no es acaso las ganas de aprender a hacer cosas y resolver problemas lo que me motivo a estudiar mi carrera?, Lo mejor era que lo podía seguir haciendo.

Nuevamente, esto es como la analogía al preguntarle a algún doctor si todavía sigue operando, lo cual denotaría la experiencia que puede proveer en la excelencia técnica que ha alcanzado a lo largo del tiempo ejecutando una y otra vez cada operación, el respeto ganado por haber dominado la maestría de manejar instrumentos y herramientas que le permiten explorar rincones que nadie más ha explorado o que puede sentirse confiado con la forma de hacerlo, sin temor y con certeza, ¿no es acaso lo mismo que queremos hacer con nuestras herramientas en el software?

No quiero que me mal entiendan, lo que quiero decir es que definitivamente sí puedes avanzar en tu carrera siendo programador, yo me veo siendo programador toda mi vida, y aprendiendo continuamente, adoptando más tecnología y más técnicas, resolviendo nuevos retos y sintiéndome estudiante constante de todos los elementos nuevos que pueda ir encontrando.

También, y de forma colateral tus percepciones aumentarán pues serás de los pocos que pueden hacer algo verdaderamente bien, incluso podrás dominar herramientas antes que muchos y usarlas para hacer cosas como nadie, lo cual, en definitiva te traerá nuevos retos que a su vez tienen sus recompensas.

No veas esto por el efecto económico, pues si lo haces podrás desviarte del verdadero encuentro con el conocimiento, hoy en día el _expertise_ de una tecnología puede ayudarte de muchas maneras, lo alcances tarde o temprano, y conforme pase el tiempo serás cada vez más valioso, muy diferente a otras profesiones en donde el rango de edad para emplearse es muy acotado, en el desarrollo de software cada experiencia cuenta más para el profesional pues tiene lo necesario para resolver una necesidad de magnitudes cada vez superiores.

== No escuches a tu padres

No quiero que me mal entiendan, solamente quiero que consideren el contexto cultural en donde en algún momento en el tiempo la obtención de un título universitario o certificado era valorado de diferente manera, en donde la percepción de tus padres o familiares que te conocen les dice que estudiando podrás alcanzar títulos, y alcanzando títulos tendrás nuevas oportunidades, y por ende te irá mejor en la vida. Pues bien, hoy tenemos casos en donde hay gente que no terminó la escuela y que ha tenido algún tipo de éxito, no me refiero solamente lo económico, en otros casos también es concerniente el aspecto social, es decir cuántas personas ha impactado, o bien incluso los descubrimientos que ha hecho en su campo o el desarrollo de alguna nueva tecnología.

Tus padres te dirán que estudies, pues es ahí en donde se encuentra el éxito, y creo estar de acuerdo con todas aquellas personas que te dicen que estudies, sin embargo, no todo el estudio se encuentra dentro de la escuela, inclusive en algunos casos el verdadero conocimiento que tú podrías ocupar en tu carrera como profesional definitivamente no lo vas encontrar ahí, sino en alguna biblioteca. La percepción es que si tú vas a la escuela, asistes, y de alguna manera te gradúas entonces te irá bien en la vida. Pues bien, puede ser así en algunos casos, más puedes encontrar oportunidades en caminos alternos que inclusive no tienen nada que ver con la escuela, pero sí con estudiar y practicar.

Comprende a tus padres que te dicen que estudies, pero también hazles comprender que el verdadero estudio y fuente de conocimiento puede encontrarse de muchas maneras.

Enfrenta una entrevista, asiste a algunas de ellas, inclusive si aún no has terminado la escuela, no importa, pues lo que vas a conocer es un proceso de selección que está allá afuera y en donde seguramente lo peor que te puede pasar es que te acepten.

Y tú debes de comprender que en el aspecto social la apariencia dicta que entre más estudies en una escuela mejores oportunidades tendrás, lo importante aquí es saber que esas oportunidades te las puedes forjar independientemente de la escuela, pero debes de estar preparado para ellas con tu estudio.

También quiero resaltar que seguramente en alguna escuela a la que asistas existen personas que te van a hacer ver las cosas de una forma diferente, incluso ayudarte a mejorarte, seguramente así será, pero lo que yo te estoy diciendo es que no dejes tu carrera solamente en las manos de aquellas personas en las cuales su trabajo es apoyarte, sino que tomes tu carrera en tus manos, enfrentes a tus padres y les hagas comprender que por lo menos el desarrollo de software tiene aspectos que muchas escuelas no ha podido abarcar como se necesita actualmente.

No digo que te reveles de una forma arrogante, sino que comprendas el hecho de que la sociedad en muchos aspectos tradicionales se rige por ciertos elementos los cuales hoy no aplican tanto como quisiéramos.

Finalmente, lo que quiero decir con todo esto es que el único responsable de tu carrera profesional eres tú.
