Para el momento en el que escribo esto tendré poco más de 17 años de haber comenzado mi carrera en el desarrollo de software, a lo largo de todo este tiempo he podido ver avances personales y profesionales qué son los que me gustaría compartir aquí, con el objetivo de que otros desarrolladores aprendan y acorten su camino basados en la experiencia que puedo ofrecerles, y también, guiarlos a través elementos muy simples que les permitan saber que pasos tomar a continuación en su carrera como profesionales de software.

He tenido la oportunidad de desarrollar en diferentes plataformas, tecnologías también, he podido aplicar algunos métodos y técnicas existentes dentro del desarrollo de software, pero siempre enfrento el mismo problema cuando de iniciar alguien se trata dentro de esta carrera.

No siempre son las mismas preguntas, generalmente algunos casos coinciden, creo que también existen confusiones por parte de algunas personas que creen que quieren dedicarse a esto cuando realmente están buscando algo diferente. A veces, tenemos que cuestionar el hecho de saber verdaderamente si se quieren dedicar a esto, exponiendo casos y contextos que les permitan identificarse a través de una cultura que hoy pretendemos formar para crear software de calidad.

En este punto de mi carrera, me doy cuenta de que deben existir ciertos elementos de conocimiento esenciales en las áreas de ciencia de computación la informática que ayuden a los aprendices a incorporarse de manera efectiva en el proceso desarrollo desarrollo de software, así también, deberían de contar con mecanismos efectivos de comunicación y una guía que les permita saber qué hacer en caso de enfrentarse ignorancia o querer avanzar su carrera, como hacer un equipo de trabajo y escuchar a otros compañeros que les permitan transmitir algún tipo de conocimiento valioso que puedan ocupar en su día a día.

Es por esto, que podido identificar algunos elementos que haciendo comunes en los equipos de trabajo los que he podido participar y que coincidentemente ha servido para poder crecer como programadores, ya sea aprendiendo nuevas tecnologías o bien creando procesos de comunicación que permiten crear software que resuelve las necesidades que nuestros contratantes exigen.

Todo lo escrito aquí, está enfocado a guiar a un aprendiz de software que tenga la pasión de emprender en camino muy largo lleno de frustraciones satisfacciones, pero tan importante como poder hacer la carrera de un abogado o doctor o cualquier otra disciplina que impacte la vida de las personas.

== A quién va dirigido

Creo que es importante mencionar que todo lo que puedas leer aquí está orientado a desarrolladores de software, sin embargo, bien podría servirte para algunos aspectos en alguna de las ramas alternas de la tecnología O de la ciencias computacionales en las que te deseas desempeñar, pero quiero hacer mucho énfasis en el hecho de que si estás pensando en ser un desarrollador de software Y te agrada mucho la tecnología, Pero sobretodo quieres aprender continuamente de todos los cambios que existen actualmente del mercado, entonces creo que lo que estoy escribiendo aquí podré ayudarte.

Lo anterior lo digo porque hoy es el día en el que yo he podido tener la oportunidad de moverme de plataformas Y de procesos de trabajo, Que me han permitido incorporar nuevos paradigmas de desarrollo, así como nuevas herramientas Y tecnología acorde a las necesidades de cada cliente, he podido explorar soluciones tecnológicas Y meto décadas que me han ayudado no solamente sino también a un grupo de personas a las cuales les he podido transmitir a resolver problemas que parecería muy complejos difíciles, pero que con un poco de preparación en ciertos elementos que podemos considerar como esenciales hemos podido realizar.

Lo descrito aquí, también ha sido comprobado a través de otras personas Campo de ir o prácticas la sugerencias descritas, O que se han acercado a mí para preguntarme que podrían hacer en dado caso de que su carrera se esté estancando O bien quieran avanzar hacia otra dirección pero siendo conscientes del posible riesgo que podrían tomar.

Yo quiero mostrarles aquí cómo es posible que puedes arriesgarte hacer ese cambio, Tomando las previsiones Y los elementos necesarios para aprender a fallar, Para aprender a aprender, y sobretodo para examinarte Como un profesional de software en algún momento en el tiempo, Y voltear hacia atrás para poder ver que tanto acecho y que tanto te falta.

Definitivamente, hay dichos coloquiales Y frases muy bien conocidas que dicen que cuanto más más conoces +ignoras, Y en el aspecto de tecnología no puede ser más cierto, pues conforme te vas entrando en el grupo de herramientas Y plataformas que existen para resolver los mismos problemas, Vas desconociendo más porque quieres aprender todo eso quieres saber cómo se usa en algunos casos también quiere saber cómo mejorarlo, Y puede ser tanta información que tal vez no sepas por dónde empezar, es por esto que quiero sentar basado en experiencia Y en la experiencia de algunas otras personas, Que sería lo más importante que deberías de hacer en algún momento del tiempo de tu carrera ya sé que estás iniciando o reiniciando en otra plataforma para poder hacer efectivo con los nuevos paradigmas y tecnologías que estés adoptando.
